public  class youngmindCalculator {
    
integer var1 = 0;
integer var2 = 0;
integer outputval;
public integer getoutput(){
    
   return outputval;
}


  public integer getvalue1() {
        
        return var1;
    }

    public void setvalue1(integer val1) {
        var1 = val1;
    }
    public integer getValue2(){
        return var2;
    }
    
    public void setValue2(integer val2) {
        var2 = val2;
    }
 String name= 'vijay';   
        
     public youngmindCalculator(){
        
     }


    public void addition(){
        
       outputval = var1 + var2;
       
    }
    
    
    
    
}